name: bus-tracker

services:
  app:
    container_name: gtfs_app
    build: ../
    restart: always
  database:
    container_name: gtfs_database
    image: postgres:18
    env_file: 
      - database.env
    volumes:
      - ./database-data:/var/lib/postgresql/18/docker
    ports:
      - 5433:5432
    restart: always
