name: Docker image builds
on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  app:
    permissions:
      packages: write
    uses: ./.github/workflows/docker-build.yml
    with:
      name: "bus-tracker"
      username: "Better-Transit-Ottawa"
      folder: "./"
    secrets:
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}